#!/usr/bin/env bash
# automatically transfers a file from a client to a server
if [ $# -ne 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$4" "$1" "$3@$2:~/"
fi
