#!/usr/bin/env bash
# automatically transfers a file from a client to a server
if [ $# -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit
fi
if [ $# -lt 5 ]
then
    scp "$1" "$3@$2:~/"
    exit
fi
scp -i "$4" "$1" "$3@$2:~/"
