#!/usr/bin/env bash
# installs and configures an nginx web server that listens on port 80
# and has a default webpage containing the string holberton school
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install nginx
echo -e "<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Holberton School Default Template</title>
  </head>
  <body>
    <header>
    </header>
    <main>
      <article>
	<h1>Holberton School ftw</h1>
	<p>Placeholder paragraph</p>
      </article>
      <aside>
      </aside>
    </main>
  </body>
</html>" | sudo tee /var/www/html/index.nginx-debian.html 1> /dev/null
sudo service nginx restart
