#!/usr/bin/env bash
# Installs and configures a haproxy server
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo "
frontend http_front
        bind *:80
        default_backend http_back

backend http_back
        balance roundrobin
        server 1699-web-01 34.73.196.89:80 check
        server 1699-web-02 54.221.178.230:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg 1> /dev/null
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
