#!/usr/bin/env bash
# displays To infinity and beyond indefinitely.
# Displays I am invincible!!! on receiving SIGTERM
trap sigtrap SIGTERM
trap inttrap SIGINT
trap cleaner EXIT
const=1
sudo touch /var/run/holbertonscript.pid
echo "$$" | sudo tee /var/run/holbertonscript.pid 1> /dev/null
function looop()
{
    while [ $const ]; do
	echo "To infinity and beyond"
	sleep 2
    done
}
function sigtrap()
{
    echo "I hate the kill command"
    exit
}
function inttrap()
{
    echo "Y U no love me?!"
    looop
}
function cleaner()
{
    sudo rm /var/run/holbertonscript.pid
    exit
}
looop
