#!/usr/bin/env bash
# loops from 1 to 20, printing 'bad luck from [country] on
# specific numbers
i=1
while [ $i -lt 21 ]; do
    echo $i
    case $i in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
	*)
	    :
    esac
    let i=i+1
done
