#!/usr/bin/env bash
# Displays time for 12 hours 59 minutes
hours=0
minutes=1
while [ $hours -lt 13 ]; do
    echo "Hour: $hours"
    while [ $minutes -lt 60 ]; do
	echo $minutes
	let minutes=minutes+1
    done
    minutes=1
    let hours=hours+1
done
